id: P66C44766
initial_creation_type: input
source_metadata:
  Title: Bodhisattva-prātimokṣa-sūtram
  Editor: Dutt, Nalinaksa
  Publisher: Calcutta Oriental Press
  Place of Publication: Calcutta
  Year: '1931'
  Bodhisattva prātimokṣa sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:15:47.197127'
last_modified_at: '2022-03-08T16:15:47.197135'
